apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
stringData:
  config.env: |-
    export MINIO_ROOT_USER="${username}"
    export MINIO_ROOT_PASSWORD="${password}"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
    export MINIO_IDENTITY_OPENID_CONFIG_URL="${keycloak.url}/realms/${realm}/.well-known/openid-configuration"
    export MINIO_IDENTITY_OPENID_CLIENT_ID=${client_id}
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET=${client_secret}
    export MINIO_IDENTITY_OPENID_DISPLAY_NAME="keycloak"
    export MINIO_IDENTITY_OPENID_SCOPES="openid,email"
    export MINIO_IDENTITY_OPENID_CLAIM_NAME="policy"
    export MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC="on"
    export MINIO_IDENTITY_OPENID_VENDOR="keycloak"
    export MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL="${keycloak.url}/admin"
    export MINIO_IDENTITY_OPENID_KEYCLOAK_REALM="${realm}"
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: ${base64encode(username)}
  CONSOLE_SECRET_KEY: ${base64encode(password)}
kind: Secret
metadata:
  name: storage-user
  namespace: minio-tenant
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: myminio
  namespace: minio-tenant
spec:
  certConfig: {}
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    nodeSelector: {}
    resources: {}
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 4
    tolerations: []
    topologySpreadConstraints: []
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
      status: {}
    volumesPerServer: 4
  priorityClassName: ""
  requestAutoCert: true
  serviceAccountName: ""
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ""
  users:
  - name: storage-user
