# This is a sample to deploy a milvus cluster with minimum cost of resources.
# It should be used for testing and development purposes only.
# Total resources required is about: 0.1 CPU, 100 MiB memory
# When deleted, all the data in the Milvus will be lost.

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  namespace: milvus-operator
  labels:
    app: milvus
spec:
  mode: cluster
  components: {}
  config: 
    common:
      security:
        authorizationEnabled: true
    minio:
      bucketName: milvus
  dependencies: 
    storage:
      external: true
      type: MinIO
      endpoint: ${minio_endpoint}
      secretRef: minio-secret
  # dependencies: 
  #   pulsar:
  #     inCluster:
  #       values:
  #         zookeeper:
  #           replicaCount: 1
  #         bookkeeper:
  #           replicaCount: 1
  #         borker:
  #           replicaCount: 1
  #         proxy:
  #           replicaCount: 1
  #   etcd:
  #     inCluster:
  #       values:
  #         replicaCount: 1
  #       deletionPolicy: Delete
  #       pvcDeletion: true
 