apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --skip-provider-button=true
        - --ssl-insecure-skip-verify
        - --provider=keycloak-oidc
        - --upstream=${upstream}
        - --oidc-issuer-url=${issuer}
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        - --insecure-oidc-allow-unverified-email=true
        - --session-cookie-minimal=true
        env:
        - name: "OAUTH2_PROXY_PROVIDER"
          value: "keycloak-oidc"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: ${client_id}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: ${client_secret}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: FApM8bW-JK_a0y0DLm45miuvohvAFl6X8b7NZt9AQz8=
        - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
          value: "*"
        - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
          value: "*"
        - name: "OAUTH2_PROXY_HTTP_ADDRESS"
          value: "0.0.0.0:4180"
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oauth2-policy
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: "oauth2-proxy"
  rules:
  - to:
    - operation:      
        # paths: ["/"]
        notPaths: ["/oauth2/*"]
  selector:
    matchLabels:
      app: istio-ingressgateway