apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-weekly
  namespace: cnpg-system
spec:
  schedule: "0 0 0 * * 0"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: cluster-cnpg
  