apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-cnpg
  namespace: cnpg-system
spec:
  instances: 3

  postgresql:
    parameters:
      shared_buffers: "256MB"

  resources:
    requests:
      memory: "1024Mi"
      cpu: 1
    limits:
      memory: "1024Mi"
      cpu: 1
  # Require 1Gi of space
  storage:
    size: 1Gi
  
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg/
      endpointURL: http://minio-gateway-service.minio-storage:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY