apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${name}-vertual-service
  namespace: ${namespace}
spec:
  hosts:
  - ${hostname}
  gateways:
  - ${name}-gateway
  http:
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.istio-system.svc.cluster.local
        port:
          number: 4180
  - route:
    - destination:
        host: ${name}-service
        port:
          number: 80
