apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kubeflow-api
  namespace: kubeflow-api
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
    to:
    - operation:
        paths: ["/v1/models/*"]