apiVersion: v1
data:
  profile-name: kubeflow-user
  user: ${email}
kind: ConfigMap
metadata:
  name: default-install-config-9h2h2b6hbk
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-user
spec:
  owner:
    kind: User
    name: ${email}
