apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-docker-socket
  namespace: kubeflow-user
spec:
  selector:
    matchLabels:
      add-docker-socket: "true"
  desc: "add docker socket"
  volumeMounts:
  - mountPath: /var/run/docker.sock
    name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
---
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-minio-secret
  namespace: kubeflow-user
spec:
  selector:
    matchLabels:
      add-minio-socket: "true"
  desc: "add minio secret"
  volumeMounts:
  - mountPath: /secret/minio
    name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: minio-secret
---
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-admin-permission
  namespace: kubeflow-user
spec:
  selector:
    matchLabels:
      add-admin-permission: "true"
  desc: "add admin permission"
  volumeMounts:
  - mountPath: /home/jovyan/.kube
    name: config
  volumes:
  - name: config
    secret:
      secretName: kubeconfig
      items:
      - key: config
        path: config