apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: spark-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark-apps
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: apache/spark:v3.1.3
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          command: ["/opt/spark/bin/spark-class"]
          args: 
            - -Dspark.history.fs.logDirectory=/opt/spark/work-dir/log
            - "org.apache.spark.deploy.history.HistoryServer"
          securityContext:
            runAsUser: 0
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080
          volumeMounts:
            - name: data
              mountPath: /opt/spark/work-dir/log
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: spark-pvc
          readOnly: true