apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    extensionProviders:
    - name: "authservice-grpc"
      envoyExtAuthzGrpc:
        service: "authservice.istio-system.svc.cluster.local"
        port: "10003"
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: "NodePort"
