apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    extensionProviders:
    - name: "authservice-grpc"
      envoyExtAuthzGrpc:
        service: authservice.istio-system.svc.cluster.local
        port: "10003"
        
  components:
    pilot:
      enabled: true
      k8s:
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
          effect: NoSchedule
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
          effect: NoSchedule
        service:
          type: "NodePort"
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: "0m"
            memory: "0Mi"
